CEPSUM2-cases-bags:
  model:
    base:
    peft:
  evaluation_metric: generation_metric
  template_id: 1
  split: valid

CEPSUM2-clothing:
  model:
    base:
    peft:
  evaluation_metric: generation_metric
  template_id: 1
  split: valid

CEPSUM2-home-appliances:
  model:
    base:
    peft:
  evaluation_metric: generation_metric
  template_id: 1
  split: valid

LCSTS:
  model:
    base:
    peft:
  evaluation_metric: generation_metric
  template_id: 1
  split: valid

AdGen:
  model:
    base:
    peft:
  evaluation_metric: generation_metric
  template_id: 1
  split: valid

KBQA:
  model:
    base:
    peft:
  evaluation_metric: dataset_kbqa_metric
  template_id: 0
  split: valid
  extra_config:
    kg_cache:
    kg_path:
    kg_search_cache:

WordSeg-Weibo:
  model:
    base:
    peft:
  evaluation_metric: dataset_cuge_segmentation_adjust_edit_distance_metric
  template_id: 0
  split: valid
  extra_config:
    max_length: 1024

ICWB-MSR:
  model:
    base:
    peft:
  evaluation_metric: dataset_cuge_segmentation_adjust_edit_distance_metric
  template_id: 0
  split: test
  extra_config:
    max_length: 1024

LCQMC:
  model:
    base:
    peft:
  evaluation_metric: accuracy_metric
  template_id: 1
  split: valid

Math23K:
  model:
    base:
    peft:
  evaluation_metric: dataset_math23k_metric
  template_id: 1
  split: valid

SIGHAN15:
  model:
    base:
    peft:
  template_id: 1
  split: test

CMeEE:
  model:
    base:
    peft:
  evaluation_metric: ner_metric
  template_id: 1
  split: test
  special-tokens:
    entity-prefix: '<unused2>'
    entity-postfix: '<unused3>'
